AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Root stack that creates the Memeify S3 output bucket, Memeify Lambda function, and API Gateway POST method
  that receives uploaded images.
Parameters:
  LambdaCodeBucket:
    Type: String
    Description: "name of S3 bucket containing the memeify lambda code (.jar)"
  LambdaCodeKey:
    Type: String
    Default: "memeify-lambdas-0.1.jar"

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

    # tells the browser to allow code from any origin to access a resource
    Cors:
      AllowOrigin: "'*'"

    # needed so that multipart/form-data will be base64 encoded by API Gateway
    BinaryMediaTypes:
      - multipart~1form-data

Resources:
  # create a bucket, with public read access, that stores memeified images
  ImageOutputBucket:
    Type: AWS::S3::Bucket

  # allows public get object permissions on the ImageOutputBucket
  PublicGetObjectPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ImageOutputBucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: ImageOutputBucket
                  - "/*"
            Principal: "*"

  MemeifyLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.cliff.memeify.Handler::handleRequest
      Runtime: java8
      Timeout: 30
      MemorySize: 256
      CodeUri:
        Bucket: !Ref LambdaCodeBucket
        Key: !Ref LambdaCodeKey
      Policies:
        # Give this lambda write access to cloudwatch logs
        - AWSLambdaBasicExecutionRole
        # Gives the lambda CRUD permissions to objects in the S3 Bucket
        - S3CrudPolicy:
            BucketName: !Ref ImageOutputBucket
      Environment:
        Variables:
          OUTPUT_BUCKET_NAME: !Ref ImageOutputBucket
          MAX_BODY_SIZE_MB: 10
      # the events that trigger this lambda function, this function will be triggered by a POST request to API Gateway
      Events:
        MemeifyApiPost:
          Type: Api
          Properties:
            Path: /memeify
            Method: Post

Outputs:
  LambdaArn:
    Value: !GetAtt MemeifyLambda.Arn
  OutputBucketName:
    Value: !Ref ImageOutputBucket

